// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCBuilder.Service.API.DBContext;

namespace PCBuilder.Service.API.Migrations
{
    [DbContext(typeof(PCBuilderContext))]
    [Migration("20201001163141_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCBuilder.Service.API.Models.Other", b =>
                {
                    b.Property<Guid>("OtherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OtherId");

                    b.ToTable("Others");
                });

            modelBuilder.Entity("PCBuilder.Service.API.Models.PCBuild", b =>
                {
                    b.Property<Guid>("PCBuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PCBuildId");

                    b.ToTable("PCBuilds");
                });

            modelBuilder.Entity("PCBuilder.Service.API.Models.PCBuildOther", b =>
                {
                    b.Property<Guid>("PCBuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OtherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PCBuildId", "OtherId");

                    b.HasIndex("OtherId");

                    b.ToTable("PCBuildOther");
                });

            modelBuilder.Entity("PCBuilder.Service.API.Models.Processor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cache")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCores")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfThreads")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProcessorBaseFrequency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCollection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Processor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6dd3edc-59c2-40b6-a983-3e9a976798b0"),
                            Cache = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "no url",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "i7",
                            NumberOfCores = 4,
                            NumberOfThreads = 4,
                            Price = 0m,
                            ProcessorBaseFrequency = 1m,
                            ProductCollection = "i7 10th gen",
                            TDP = 100
                        });
                });

            modelBuilder.Entity("PCBuilder.Service.API.Models.PCBuildOther", b =>
                {
                    b.HasOne("PCBuilder.Service.API.Models.Other", "Other")
                        .WithMany()
                        .HasForeignKey("OtherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCBuilder.Service.API.Models.PCBuild", "PCBuild")
                        .WithMany("PCBuildOthers")
                        .HasForeignKey("PCBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
