// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wishlist.Service.API.DBContext;

namespace Wishlist.Service.API.Migrations
{
    [DbContext(typeof(WishlistContext))]
    [Migration("20200916224238_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wishlist.Service.API.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OccasionId")
                        .IsUnique()
                        .HasFilter("[OccasionId] IS NOT NULL");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Wishlist.Service.API.Models.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88dfb763-1e5f-43fb-b8bb-7abc20eba4b0"),
                            Description = "There is no occasion, but don't forget about yourself.",
                            Name = "NoOccasion"
                        },
                        new
                        {
                            Id = new Guid("dd86dc9b-5cd2-4548-83bb-4cd233dc6f26"),
                            Description = "Someone celebrates birthday, don't forget about a nice present.",
                            Name = "BirthdayPresent"
                        },
                        new
                        {
                            Id = new Guid("2b9fb10a-a0c2-4e62-957b-3262a2428c5d"),
                            Description = "Christmas time, there is no better time for presents.",
                            Name = "ChristmasPresent"
                        },
                        new
                        {
                            Id = new Guid("947c82e9-e6a0-478d-98b0-ca05609f4c8e"),
                            Description = "Need more stuf, movement is great opportunity to rid of old things.",
                            Name = "Movement"
                        },
                        new
                        {
                            Id = new Guid("bea093d4-7deb-4766-bcb7-00cf48f468ad"),
                            Description = "Any other situation you didn't think of.",
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("Wishlist.Service.API.Models.Entity", b =>
                {
                    b.HasOne("Wishlist.Service.API.Models.Occasion", "Occasion")
                        .WithOne("Entities")
                        .HasForeignKey("Wishlist.Service.API.Models.Entity", "OccasionId");
                });
#pragma warning restore 612, 618
        }
    }
}
